## Objective: Learning to solve basic Python problems

Prerequisites: Module 1 listed @ https://www.appliedaicourse.com/course/11/Applied-Machine-learning-course - SQL

Tackle few simple problems relvant to AI/ML
    - Break a problem into smaller sub-problems.
    - Connecting the dots from sub-problems to coding-concepts.
    - Code-walkthrough + Putting it all together.
    - More focus on common errors and mistakes + reading function reference + fixing bugs
    - Exercise-problems for practice.
    - Introduce new concepts as we need.
    - Good programmers may not benifit much from this session.
    

### Problem 1: Add two randomly generated NumPy matrices using loops 
    - Sub-problems
    - Subproblems ---> coding concepts
    - Code-walkthrough + Mistakes
    - Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

In [1]:
# create random matrix A1 of size 5X4.
### Google " numpy create random matrices " & Read through the top 4-5 links
### https://www.codespeedy.com/how-to-create-matrix-of-random-numbers-in-python-numpy/

import numpy as np
A1 = np.random.rand(5,4) # read documentation to understand the params. Google "np.random.rand reference" ---> https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html

##COMMON-ERROR: np.random.rand(4,5)
##COMMON_ERROR: 

print(A1) # always print to ensure that everyhitng works fine.

print(A1.shape)


[[0.96456332 0.12211174 0.99017456 0.7894821 ]
 [0.36457976 0.48624075 0.68889511 0.17541113]
 [0.99835823 0.94831367 0.573953   0.0906775 ]
 [0.81307936 0.66072197 0.77578594 0.94216739]
 [0.02878636 0.28985786 0.6521746  0.55447172]]
(5, 4)


In [2]:
print(A1.shape); #COMMON-ERROR

(5, 4)


In [3]:
print(type(A1)); # COMMON-ERROR

<class 'numpy.ndarray'>


In [4]:
print(type(A1));

<class 'numpy.ndarray'>


In [5]:
# Read through the attributes and methods in numpy.ndarray class
## Google "numpy.ndarray" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

## Pre-Google programmers: Read reference docs.

In [6]:
# Create random Matrix A2
A2 = np.random.rand(5,4);

print(A2);

[[0.13298903 0.17000869 0.77849825 0.74855954]
 [0.54338112 0.96677514 0.01783392 0.73385855]
 [0.84350398 0.54590458 0.01208175 0.69947361]
 [0.70438668 0.60557631 0.16071015 0.45344739]
 [0.00638158 0.10923074 0.24971954 0.34172388]]


In [7]:
# Add element wise using loops A1+A2 = B

## Google "Accessing i,j th element in an ndarray" ---> https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html
print(A1[2,3]);


0.09067750029851862


In [8]:
print(A1[2,3]); #COMMON_ERROR

0.09067750029851862


In [9]:
B= A1+A2; # using + operator on ndarrays
print(B); 

[[1.09755235 0.29212043 1.7686728  1.53804164]
 [0.90796088 1.45301589 0.70672903 0.90926968]
 [1.84186222 1.49421824 0.58603475 0.79015111]
 [1.51746604 1.26629828 0.93649609 1.39561478]
 [0.03516795 0.3990886  0.90189414 0.8961956 ]]


In [10]:
(r,c) = A1.shape;
print(r,c)

5 4


In [11]:
#B[i,j] = A1[i,j] + A2 [i,j] 

for i in range(r):
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[1.09755235 0.29212043 1.7686728  1.53804164]
 [0.90796088 1.45301589 0.70672903 0.90926968]
 [1.84186222 1.49421824 0.58603475 0.79015111]
 [1.51746604 1.26629828 0.93649609 1.39561478]
 [0.03516795 0.3990886  0.90189414 0.8961956 ]]


In [12]:
# OPTIMIZATION: Pre-allocate matrix B
B = np.zeros((5,4)); # COMMON-ERROR

In [13]:
#Google "np.zeros" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html
B = np.zeros((5,4))

for i in range(r): # same code as earlier
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[1.09755235 0.29212043 1.7686728  1.53804164]
 [0.90796088 1.45301589 0.70672903 0.90926968]
 [1.84186222 1.49421824 0.58603475 0.79015111]
 [1.51746604 1.26629828 0.93649609 1.39561478]
 [0.03516795 0.3990886  0.90189414 0.8961956 ]]


In [14]:
# Time Complexity: ?
# Space Complxiety: ?

#### Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

HINT: B[i,j,k] = A1[i,j,k] + A2[i,j,k]
****************************************************************************************************************
****************************************************************************************************************
****************************************************************************************************************

### Problem 2: Find if a given 2D-point is inside (or) outside a circle 
    - Subproblems.
    - Subproblems --> coding concepts.
    - putting it all together.
    - Exercise: Find if a given 2D point is inside (or) outside a rectangle ? 
   

In [15]:
## input circle (C) and point(P)

# input circle params
# Google " input multiple values python 3" ---> https://www.geeksforgeeks.org/input-multiple-values-user-one-line-python/
print("Enter Cx, Cy, r:");
(Cx, Cy, r) = input().split();

print(Cx, Cy, r); # always cross check using print statements

Enter Cx, Cy, r:
12 5 18
12 5 18


In [16]:
# input circle params
## Google "python input multiple values in single line" ----> https://www.tutorialspoint.com/how-to-input-multiple-values-from-user-in-one-line-in-python
## TRY MULTIPLE APPROACHES and learn from each attempt.

Cx, Cy, r = input("Enter Cx, Cy, r:").split();



Enter Cx, Cy, r:12 5 18


In [17]:
# Google " SyntaxError: invalid syntax input Python3 string" --> https://stackoverflow.com/questions/25174925/syntax-error-for-input
Cx, Cy, r = input("Enter Cx, Cy, r:").split();


Enter Cx, Cy, r:12 5 18


In [18]:
print(Cx, Cy,r)

12 5 18


In [19]:
# Input Px, Py

Px, Py = input("Enter Px, Py:").split()
print(Px, Py);

Enter Px, Py:5 4
5 4


In [20]:
# Check if P lies in C.

## String to Float. Very important to note that split() returns Strings
Cx = float(Cx);
Cy = float(Cy);
r =float(r);
Px= float(Px);
Py = float(Py);

import math 

d = math.sqrt( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("P in C")
else:
    print("P NOT in C")

7.0710678118654755
P in C


#### Exercise: Find if a point is inside or outside a rectangle.

HINT: How do you represent a rectangle?

********************************************
********************************************
********************************************

### Problem 3: NumPy ndarray manupualtion operations


In [21]:
# 1. Reshape matrices: Very COMMON-ERRORS in Assignments
A = np.random.rand(5,4);
print(A);


[[0.42672226 0.87948611 0.51011749 0.50005732]
 [0.76686089 0.22914142 0.72424851 0.11380093]
 [0.17529024 0.83541603 0.97696418 0.95371396]
 [0.59680966 0.86957435 0.60756443 0.62522891]
 [0.80880744 0.95870056 0.66768033 0.45832695]]


In [22]:
## reshape into a vector row-major-order
###https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html 
### Patiently read the documentation and try alternaive params
print( np.reshape(A, 20, 'C'))


[0.42672226 0.87948611 0.51011749 0.50005732 0.76686089 0.22914142
 0.72424851 0.11380093 0.17529024 0.83541603 0.97696418 0.95371396
 0.59680966 0.86957435 0.60756443 0.62522891 0.80880744 0.95870056
 0.66768033 0.45832695]


In [23]:
print( np.reshape(A, 20, 'F'))

[0.42672226 0.76686089 0.17529024 0.59680966 0.80880744 0.87948611
 0.22914142 0.83541603 0.86957435 0.95870056 0.51011749 0.72424851
 0.97696418 0.60756443 0.66768033 0.50005732 0.11380093 0.95371396
 0.62522891 0.45832695]


In [24]:
print( np.reshape(A, (4,5), 'C'))

[[0.42672226 0.87948611 0.51011749 0.50005732 0.76686089]
 [0.22914142 0.72424851 0.11380093 0.17529024 0.83541603]
 [0.97696418 0.95371396 0.59680966 0.86957435 0.60756443]
 [0.62522891 0.80880744 0.95870056 0.66768033 0.45832695]]


In [25]:
print( np.reshape(A, (4,-1), 'C'))

[[0.42672226 0.87948611 0.51011749 0.50005732 0.76686089]
 [0.22914142 0.72424851 0.11380093 0.17529024 0.83541603]
 [0.97696418 0.95371396 0.59680966 0.86957435 0.60756443]
 [0.62522891 0.80880744 0.95870056 0.66768033 0.45832695]]


In [26]:
print( np.reshape(A, (-1,5), 'C'))

[[0.42672226 0.87948611 0.51011749 0.50005732 0.76686089]
 [0.22914142 0.72424851 0.11380093 0.17529024 0.83541603]
 [0.97696418 0.95371396 0.59680966 0.86957435 0.60756443]
 [0.62522891 0.80880744 0.95870056 0.66768033 0.45832695]]


#### Exercise: take a tensor of size 4X5X6 and convert it into a tensor of vector and matrix (10X12).

In [27]:
#2. Stacking
A = np.random.rand(5,4);
print(A);

B= np.random.rand(5,2);
print(B)


[[0.65668848 0.3993223  0.32139499 0.39799368]
 [0.21224704 0.43531026 0.80523461 0.20091783]
 [0.24575764 0.02226443 0.57109022 0.88773109]
 [0.43340346 0.55936818 0.51973195 0.03283444]
 [0.18458977 0.01298982 0.17833816 0.11818833]]
[[0.68845583 0.99079558]
 [0.02434171 0.10890952]
 [0.76760483 0.17835643]
 [0.34807383 0.98613066]
 [0.49149536 0.77290165]]


In [28]:
C = np.hstack((A, B)); # read documentation carefully
print(C)

[[0.65668848 0.3993223  0.32139499 0.39799368 0.68845583 0.99079558]
 [0.21224704 0.43531026 0.80523461 0.20091783 0.02434171 0.10890952]
 [0.24575764 0.02226443 0.57109022 0.88773109 0.76760483 0.17835643]
 [0.43340346 0.55936818 0.51973195 0.03283444 0.34807383 0.98613066]
 [0.18458977 0.01298982 0.17833816 0.11818833 0.49149536 0.77290165]]


In [29]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.vstack((A, B));
print(C)

[[0.17826053 0.43250768 0.19476911 0.57691055]
 [0.57043687 0.42962317 0.03688855 0.94468286]
 [0.01616704 0.82765372 0.4659424  0.9558912 ]
 [0.88059892 0.42078486 0.63401026 0.84743651]
 [0.14065368 0.15707019 0.97097325 0.68067365]]
[[0.0477486  0.25736404 0.94610903 0.49482497]
 [0.79280602 0.86832371 0.44532749 0.89396663]
 [0.42744579 0.96342129 0.92094473 0.61435282]
 [0.88199374 0.68239669 0.49899168 0.69362155]]
[[0.17826053 0.43250768 0.19476911 0.57691055]
 [0.57043687 0.42962317 0.03688855 0.94468286]
 [0.01616704 0.82765372 0.4659424  0.9558912 ]
 [0.88059892 0.42078486 0.63401026 0.84743651]
 [0.14065368 0.15707019 0.97097325 0.68067365]
 [0.0477486  0.25736404 0.94610903 0.49482497]
 [0.79280602 0.86832371 0.44532749 0.89396663]
 [0.42744579 0.96342129 0.92094473 0.61435282]
 [0.88199374 0.68239669 0.49899168 0.69362155]]


In [30]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.vstack((A, B)); #Vertical stacking
print(C)

[[0.01052414 0.24164463 0.41584368 0.34234349]
 [0.73880617 0.82498408 0.94954955 0.38375514]
 [0.51425303 0.07892721 0.0120028  0.6120063 ]
 [0.51203604 0.21915694 0.91375968 0.50737459]
 [0.96335424 0.10711068 0.32572032 0.96913997]]
[[0.99345971 0.26559329 0.42407095 0.60916786]
 [0.5975687  0.67292475 0.42118595 0.65490794]
 [0.15403085 0.75798782 0.02591257 0.97454259]
 [0.09204006 0.33324741 0.13803776 0.39232031]]
[[0.01052414 0.24164463 0.41584368 0.34234349]
 [0.73880617 0.82498408 0.94954955 0.38375514]
 [0.51425303 0.07892721 0.0120028  0.6120063 ]
 [0.51203604 0.21915694 0.91375968 0.50737459]
 [0.96335424 0.10711068 0.32572032 0.96913997]
 [0.99345971 0.26559329 0.42407095 0.60916786]
 [0.5975687  0.67292475 0.42118595 0.65490794]
 [0.15403085 0.75798782 0.02591257 0.97454259]
 [0.09204006 0.33324741 0.13803776 0.39232031]]


In [31]:
# 3D tensors
A = np.random.rand(5,4,3); # (height, width, colors) in images is a good way to think of this
print(A.shape);

B= np.random.rand(5,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 3, 3)
(5, 7, 3)


In [32]:
# 3D tensors vstack
A = np.random.rand(5,4,3); # (height, width, colors) in images
print(A.shape);

B= np.random.rand(2,4,3);
print(B.shape)

C = np.vstack((A, B));
print(C.shape)

(5, 4, 3)
(2, 4, 3)
(7, 4, 3)


#### Exercise: Achieve the above tranaomfrs using numpy.concatenate [https://numpy.org/doc/1.18/reference/generated/numpy.concatenate.html#numpy.concatenate]
***********
***********
***********
***********


### Problem-4: Find peaks/max in an list
- problem definition


In [33]:

A = [1,3,4,5,7,6,4,5,10,1];
print(A)

[1, 3, 4, 5, 7, 6, 4, 5, 10, 1]


In [34]:
# Peaks: 7,10
# Peak: A[i-1] <= A[i] >= A[i+1]

for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7
10


In [35]:
print(len(A));

10


In [36]:
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7
10


In [37]:
# There is a bug in the above solution. Find it...


In [38]:
A = [11,3,4,5,7,6,4,5,10,15];

for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7


In [39]:
# what about 11 and 15?

# boundary case
if A[0] >= A[1]:
    print(A[0])
    
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

# boundary case
if A[len(A)-1] >= A[len(A)-2]:
    print(A[len(A)-1])


11
7
15


In [40]:
# LESSON: Donot forget boundary cases

#Question: Time Complexity = ?

#### Exercise: 
1. Find peaks which are max values in a window of size 2 on both sides.
2. Use scipy.signal.find_peaks [https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html]

Additioanl reading: More efficient algos @ http://courses.csail.mit.edu/6.006/spring11/lectures/lec02.pdf

### Problem 5: Permutations of a list
- Problem definition: lst = [1,2,3]

In [41]:
# Using libraries
from itertools import permutations 
  
p = permutations([1, 2, 3]) # refer: https://docs.python.org/3/library/itertools.html#itertools.permutations

# what is an iterable in Python [https://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/Iterables.html]

# print the permutations
for i in list(p): 
    print(i) 

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


In [42]:
# No fun!
# Write your own code. Any suggestions?
# Break the problem into smaller sub-problems

In [43]:
[1,2,3]
[1,3,2]
[2,1,3]
[2,3,1]
[3,1,2]
[3,2,1]

[3, 2, 1]

In [44]:
# source: https://stackoverflow.com/questions/13109274/python-recursion-permutations

def permutation(s):
   if len(s) == 1:
     return [s]

   perm_list = [] # resulting list
   for a in s:
     remaining_elements = [x for x in s if x != a]
     z = permutation(remaining_elements) # permutations of sub-list

     for t in z:
       perm_list.append([a] + t)

   return perm_list

s = [1,2,3];
p = permutation(s);
print(p)

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]


#### Exercise: [Combinations] All possible ways to pick 3 elements out of 5 elements

- HINT: Use recursion.
- Google "combinations in Python"

### Practice, practice and practice..

- Optional  Assignments at AAIC: https://go.aws/2JrmV4A [Functions] , https://drive.google.com/file/d/1VB3wJSt_Mq0HLP9uaqgsZBR4BLMFnkmY/view [Pandas]

- Basic Python: https://www.geeksforgeeks.org/python-programming-examples/
- NumPy: https://www.w3resource.com/python-exercises/numpy/index.php
